# Generated by Django 5.0.3 on 2024-04-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='car_price',
            new_name='borrow_price',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='brand',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='car_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='car_quantity',
            new_name='quantity_available',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='car',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='car',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='books',
            name='car_name',
        ),
        migrations.AddField(
            model_name='books',
            name='book_name',
            field=models.CharField(default='Unnamed Book', max_length=100),
        ),
    ]
